name: amr-core
dependencies:
  - cytoolz
  - dask
  - numpy
  - pandas
  - Pillow
  - scipy
  - scikit-image
  - tensorflow>=1.7
  - tensorflow-gpu
  - tqdm
  - toolz
  - tabulate
  - pip:
    - tflearn
    - google-cloud==0.32.0
    - tensorflow-hub


